### ISSUE TITLE
Endpunkt für Routen suche

### ISSUE THREAD

**Issue by darenegade** [darenegade/BikeBattleBackend#3]
Man bekommt alle öffentlichen Routen und die seiner Freunde.

Für die Suche muss ein Standort und die Umkreisgröße übergeben werden.

**Comment by darenegade** [comment]
Umstieg auf Mongo notwendig, um hässlichen Code zu vermeiden:
https://blog.codecentric.de/2012/03/spring-data-geodaten-suche-mit-mongodb/

**Comment by NeelzDev** [comment]
Okay. Wie leicht lässt sich denn unsere derzeitige Datenhaltung zu mongodb migrieren?

**Comment by darenegade** [comment]
Easy, hab ich schon gemacht. Nur ein paar Annotationen anpassen. Die REST Schnittstelle bleibt gleich, wodurch die API nicht angepasst werden muss.
Wenn du dir den Artikel von oben anschaust, dann siehst du, wie einfach man nun nach Locations in einem Umkreis suchen kann und vor allem wie schnell es geht. 😄

**Comment by NeelzDev** [comment]
Sehr gut. Hab ich kurz überflogen, sah echt simpel aus :+1:
